### ISSUE TITLE
asadmin password file permissions too open

### ISSUE THREAD

**Issue by robshep** [fatmcgav/fatmcgav-glassfish#44]
Hi,

From the class manifest: glassfish::create_asadmin_passfile:

https://github.com/fatmcgav/fatmcgav-glassfish/blob/v0.5.0/manifests/create_asadmin_passfile.pp#L39

The permissions for this file are world readable.

I would have thought that given a user can be supplied throughout, 
the permission of:  

0600 (only user readable) 

would be more appropriate?

**Comment by fatmcgav** [comment]
Agreed... PR welcome.. Or I'll try and get to it soon... :-)

**Comment by robshep** [comment]
Unfortunately I am not a module developer and so can't yet contribute much in the way of changes (although I reckon I could manage this one :) )   

For what it's worth - I've discovered that there is too much I would need to change in this module for me to be able to use it.    For us, being able to utilise --domain-dir in 'create-domain' and 'start-domain' is required. Shall I make an ER for this?

Cheers

**Comment by fatmcgav** [comment]
Hehe, np... 

Would be interested in looking at what's missing currently that would help you guys to use it.. 

Feel free to raise a new issue with command line examples and usage reqs, and I'll see what I can work up...

**Comment by fatmcgav** [comment]
Fix for file permissions committed in 8c6abb0. Cheers for raising.
