### ISSUE TITLE
Virtual Resource references issue

### ISSUE THREAD

**Issue by ITler** [fatmcgav/fatmcgav-glassfish#52]
Catalogue compilation will fail due to incompatible Virtual Query definitions with Puppet 4+.

    Class['glassfish::path'] -> Create_domain <| |>
    Class['glassfish::path'] -> Create_cluster <| |>
    Class['glassfish::path'] -> Create_node <| |> 

Should be

    Class['glassfish::path'] -> Glassfish::Create_domain <| |>
    Class['glassfish::path'] -> Glassfish::Create_cluster <| |>
    Class['glassfish::path'] -> Glassfish::Create_node <| |> 

There are multiple files affected. Functional tests pending.

**Comment by fatmcgav** [comment]
Cheers for flagging these up... I should probably add Puppet 4.x to the TravisCI matrix to see these...

**Comment by ITler** [comment]
I think, this issue is not specific to Puppet 4.x. Some of your files already have the correct Virtual Queries. Maybe you missed those references while refactoring.

**Comment by fatmcgav** [comment]
Yeh, I suspect it's been over-looked when re-factoring... However the code works in production with Puppet 3.7, so I'm guessing it's a tightening of the rules in future parser that's done it :) 

Cheers

**Comment by fatmcgav** [comment]
Fixed by #54
