### ISSUE TITLE
Puppet 4 namespace issue

### ISSUE THREAD

**Issue by semitry** [fatmcgav/fatmcgav-glassfish#58]
puppet4 is unable to find resources Create_cluster, Create_node and Create_domain unless Glassfish:: is prepended.

**Comment by fatmcgav** [comment]
@semitry Can you confirm which classes you had to make the modifications in? 

As I'm struggling to find any resources references that aren't correctly namespaced...

**Comment by semitry** [comment]
@fatmcgav okay, I figured out my problem.  I downloaded the develop branch from github and not the version from the forge.  I just downloaded the latest from the forge and that appears to be correct.  I'm sorry.  Close this.

**Comment by fatmcgav** [comment]
@semitry develop should have the same code base tbh, as the 0.7.0 release was ultimately released from it... Maybe an old commit? 

But yeh, using the version from the Forge makes most sense. :)
